//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string name { get; set; }
        public string sef { get; set; }
        public string text { get; set; }
        public Nullable<int> plu { get; set; }
    }
}
