//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int id { get; set; }
        public string name { get; set; }
        public string tax_number { get; set; }
        public string tax_office { get; set; }
        public Nullable<int> phone { get; set; }
        public string adress { get; set; }
        public string auth_name { get; set; }
        public Nullable<int> auth_phone { get; set; }
        public Nullable<int> tax_rate { get; set; }
        public Nullable<int> tax_rate_is_inc { get; set; }
        public Nullable<int> sale_print { get; set; }
        public string barcode_paper_width { get; set; }
        public string barcode_paper_height { get; set; }
        public Nullable<int> sales_screen { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<System.DateTime> licence_end_date { get; set; }
    }
}
