//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currenty
    {
        public int id { get; set; }
        public string company_id { get; set; }
        public string email { get; set; }
        public string adress { get; set; }
        public string tax_office { get; set; }
        public string tax_number { get; set; }
        public Nullable<int> current_type { get; set; }
        public Nullable<int> point_card_number { get; set; }
        public string auth_name { get; set; }
        public string auth_gsm { get; set; }
        public Nullable<decimal> risk_limit { get; set; }
        public Nullable<int> sms_notification { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
    }
}
