//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CloudEntities : DbContext
    {
        public CloudEntities()
            : base("name=CloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank> Banks { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Current_Details> Current_Details { get; set; }
        public DbSet<Currenty> Currenties { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<Warehouse> Warehouses { get; set; }
    }
}
