//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string auth_name { get; set; }
        public string email { get; set; }
        public string salt { get; set; }
        public Nullable<int> password { get; set; }
        public string token { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> is_admin { get; set; }
        public Nullable<int> store_admin { get; set; }
        public Nullable<int> notification { get; set; }
        public Nullable<int> confirmation { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<System.DateTime> licence_start_date { get; set; }
        public Nullable<System.DateTime> licence_end_date { get; set; }
    }
}
