//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcoS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string name { get; set; }
        public string auth_name { get; set; }
        public string auth_phone { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
    }
}
